### ISSUE TITLE
Diluc a4 passive always on

### ISSUE THREAD

**Issue by HanSeoulOh** [genshinsim/gcsim#100]
https://github.com/genshinsim/gcsim/blob/3f5166b6676f80711a3072ea3f8d94f9fe908a08/internal/characters/diluc/abil.go#L115

This should only be for a4.. guess it's not too big of a deal though if your diluc is leveled

**Comment by srliao** [comment]
Sim for now assumes everyone lvls their char to 60/70 at least.

could be something to revisit in future if there's a need for this
