### ISSUE TITLE
show stam (and maybe other stats) in debug view somehow

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#102]

**Comment by Tsym-or-Tysm** [comment]
What exactly is this issue about? Stats are now calculated and shown at frame -1 and stamina has always been shown in the actions log.

![image](https://user-images.githubusercontent.com/84653157/149441909-3a9cfaab-2114-431e-9ef3-3634342f0fe9.png)

**Comment by HanSeoulOh** [comment]
Is this a UI thing? @srliao

**Comment by srliao** [comment]
Nope. This is logging. Forgot what this one is about though…. Closing until someone complains
