### ISSUE TITLE
About Chinese translation.

### ISSUE THREAD

**Issue by a5680737** [genshinsim/gcsim#1092]
There are many players in Chinese genshin forum who are eager to use gcsim to simulate team DPS, but due to their English level, they are difficult to use it. I am a Chinese developer and willing to work in Chinese translation. Can I participate in this work? And how to start?

**Comment by a5680737** [comment]
Didn't notice that there are already Chinese version.

**Comment by a5680737** [comment]
Didn't notice that there are already Chinese version.

**Comment by srliao** [comment]
translations are a bit outdated at the moment. there's a large UI overhaul currently in the works so after that we'll probably be looking for assistance with translations
