### ISSUE TITLE
Keqing C1 should be 2 hits

### ISSUE THREAD

**Issue by jdy18** [genshinsim/gcsim#1119]
Keqing C1 should be 2 hits

![image](https://user-images.githubusercontent.com/52999149/203301700-048212de-31f4-4e5c-8c6b-0e9e1d674828.png)

**Comment by k0l11** [comment]
You need to specify the number of hits via `skill[hits=2];` on the recast for 2 hits. The default is hits=1.

**Comment by jdy18** [comment]
> You need to specify the number of hits via `skill[hits=2];` on the recast for 2 hits. The default is hits=1, which makes sense as sensible default to me.

Keqing C1: Recasting Stellar Restoration while a Lightning Stiletto is present causes Keqing to deal 50% of her ATK as AoE Electro DMG at the start point **and** terminus of her Blink.

Even if I use skill[hits=2], there is also only 1 hit.
![image](https://user-images.githubusercontent.com/52999149/203320192-c4ed7348-1747-4e58-8db5-a3caa8ec1a80.png)

**Comment by soloxcx** [comment]
it’s cause the param is `skill[c1=2]` actually

**Comment by jdy18** [comment]
> it’s cause the param is `skill[c1=2]` actually



> 

Thanks!
