### ISSUE TITLE
Cannot trigger Aloy's coil

### ISSUE THREAD

**Issue by QyInvoLing** [genshinsim/gcsim#1125]
zhongli skill[hold=1];
shenhe skill[hold=1];
aloy skill;
kazuha skill[hold=1],high_plunge;
Then aloy's normal attack should be cyro enchanted, but when I check debug info, I found aloy attacking without cyro enchantment......

**Comment by RarePossum** [comment]
Currently, movement due to grouping is not simulated. To get Aloy's Infusion, use `aloy skill[bomblets=6, bomblet_coil_stacks=6];`
