### ISSUE TITLE
Cinnabar's passive isn't dynamic on characters who snapshot

### ISSUE THREAD

**Issue by MrPillow1** [genshinsim/gcsim#1136]
In-game, Cinnabar Spindle's passive is dynamic. However, in the sim, if a character sanpshots their Elemental Skill dmg,  Cinnabar Spindle's passive will continue using the snapshotted stats.

**Comment by k0l11** [comment]
Can you provide a short video?

**Comment by MrPillow1** [comment]
https://discord.com/channels/763583452762734592/1051592932538449991/1051598315252355172

**Comment by MrPillow1** [comment]
it might be relevant to check how the sim handles other flat dmg and snapshotting ability interactions. this cinnabar-albedo bug is likely just a special case.
