### ISSUE TITLE
adjust Amber Q logic

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#1173]
Her Q should be positioned on the closest enemy. Then the following things should happen:
- fire 1 arrow at 2.6m from the Q center every 0.4s for 2s (5 arrows total)
- fire 1 arrow at 2.6m from the Q center every 0.6s for 2s (3 arrows total)
- fire 1 arrow anywhere between 0.1 and 2.6m distance from the Q center every 0.2s for 2s (10 arrows total) 

This is assuming A4. For non-A4 replace 2.6m with 2m. Related: #1112.

**Comment by unleashurgeek** [comment]
Note: current logic is 1 arrow short in the first group and last group (should be using `<=` in for loop conditional)
