### ISSUE TITLE
Potential Proposal for Adding Delays Onto Actions

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#119]
The sim tends to run fast compared to in-game, which can lead to a lot of desync and manual jumps/dashes/waits needing to be added. We may want to have some kind of system to more easily allow for adding these into the sim, or have some kind of global system with "ideal" and "human-doable" frames.

Current status is that we shelve this for the future, until end users start complaining more. 

Reference discord convo.

Start: https://discord.com/channels/845087716541595668/886303126242623540/926327273173446666

End: https://discord.com/channels/845087716541595668/886303126242623540/926336862556143676

**Comment by srliao** [comment]
related to #97

**Comment by k0l11** [comment]
The "system" is currently to overwrite the execute_action system function in order to increase frames for actions, so closing. See https://docs.gcsim.app/reference/system_functions#execute_action.
