### ISSUE TITLE
Xiao C6 does not reapply Cooldown to skill.

### ISSUE THREAD

**Issue by RarePossum** [genshinsim/gcsim#1202]
Xiao's C6 resets the cooldown of his skill when triggered. Then he gets his 3 free skills. But after that, the cooldown is not reset, so he can use his skill a 4th time for free.

https://gcsim.app/v3/viewer/share/bcec1400-1723-4415-a954-9ac2bee1506f

![image](https://user-images.githubusercontent.com/48541822/210282334-bb72f4eb-ad4d-44d7-b595-7bc9e420096a.png)

**Comment by k0l11** [comment]
This is working correctly.
