### ISSUE TITLE
Prism.js (config editor highlighting) should be moved to this repository

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#1237]
Reasons are already outlined in #1162.
https://github.com/srliao/prism

**Comment by k0l11** [comment]
From quick research, I don't think it's possible to use Prism.js / highlight.js with a custom language definition without forking the repository. Since we want to keep the forked repository up-to-date while keeping it inside of the gcsim repository, we can only include it via `git subtree`, but this would clutter our commit history with commits from the Prism.js / highlight.js folks. I think the best move going forward is to either implement the highlighting ourselves or choose a different package that allows for defining custom languages for highlighting without having to fork it.

**Comment by unleashurgeek** [comment]
Short term, best is to just fork the repository since we do not currently keep it up to date anyway.

Long term, I agree we need to find a different highlighting package that is better designed for custom languages

**Comment by k0l11** [comment]
fixed in #2060 by removing the prismjs fork dependency entirely
