### ISSUE TITLE
Refactor common na hook logic

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#1242]
In order to reduce coupling, the information that is being setup here: https://github.com/genshinsim/gcsim/blob/93664044b32a13f41f172aa803059b5b09819688/internal/common/normalattackstate.go#L23 should be moved to each individual character. This can be achieved by translating the "5% of NA state length" into just the full state length, have each char supply this state length with every normal attack (with some sane defaults for other actions) and then use that inside of the common NA hook to check whether more than 5% of the state length is already over.

That per-char information could be stored here:
https://github.com/genshinsim/gcsim/blob/97e8e28c0e21004127ac33dddc62faa91331fff7/pkg/core/action/action.go#L11

**Comment by Charlie-Zheng** [comment]
Also need to include a NA start time or something for Yelan's 0% timings
