### ISSUE TITLE
fix Itto normal counter not being reset correctly

### ISSUE THREAD

**Issue by MrPillow1** [genshinsim/gcsim#1267]
This effect "Additionally, Itto's Normal Attack combo does not immediately reset after sprinting or using his Elemental Skill" currently has a buggy implementation. 

The bug is that "c.savedNormalCounter" is not being reset properly. Example: At frame 1835 here (https://gcsim.app/v3/viewer/share/fd8f786c-a782-4e30-ae27-32c8220e0b49), Itto should be doing N0 instead of N1. The sim thinks he should be doing an N1 here because the previous action was Ushi, but it should've been an N0 because the action before Ushi wasn't a Normal Attack. 

Additionally, any fixes should adhere to these findings in the TCL: https://library.keqingmains.com/evidence/characters/geo/arataki-itto#itto-na-combo-non-reset-mechanics

edit: the above tcl entry is currently wrong. should hold off from this issue for the time being

**Comment by k0l11** [comment]
> the above tcl entry is currently wrong. should hold off from this issue for the time being
Can you please clarify?

**Comment by k0l11** [comment]
Let me know if the PR is wrong.

**Comment by MrPillow1** [comment]
> My current understanding of the problem is that only chains of skill uses and single dashes should allow for saving the NA counter. Is this wrong?

Yes this is wrong, since it's been shown that NA1 E D NA2 is possible. See my convo with Shizuka starting from this message https://discord.com/channels/845087716541595668/845087716541595671/1075218275635568691

As things currently stand this mechanic needs more testing.

**Comment by k0l11** [comment]
Does it really need more testing? If I change the PR to allow E D then it should be correct for the common cases, no?

**Comment by k0l11** [comment]
feel free to reopen if this is still an issue
