### ISSUE TITLE
Amber's Baron Bunny should be implemented as a Gadget

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#1282]
Amber's Baron Bunny:
- can only hold Cryo durability in normal circumstances 
- this can be picked up by absorb checks
- properties from Dendro MC's Q gadget also apply here: 
  - not able to proc OnReaction affects on Baron Bunny
  - ~~only Sucrose E and Faruzan Pressurized Collapse can interact with Baron Bunny for a Swirl (don't forget to set the durability to 50 for the incoming anemo attack)~~
  - once it has Cryo durability, any elemental application except Anemo (see above) and Dendro (because it has no reaction with Cryo) can interact with it for a reaction
  - ...

https://library.keqingmains.com/evidence/characters/pyro/amber#baron-bunnys-aura

**Comment by Charlie-Zheng** [comment]
> only Sucrose E and Faruzan Pressurized Collapse can interact with Baron Bunny for a Swirl (don't forget to set the durability to 50 for the incoming anemo attack!)

I'm pretty sure all Anemos can swirl baron bunny/lea lotus lamp. Guoba is the guy that has special interactions.

**Comment by k0l11** [comment]
Hmm, I wonder if that means Sucrose/Faruzan E durability is unaffected. Just leave the durability untouched and add a TODO.
