### ISSUE TITLE
Weapon Parameters are Not Working

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#130]
Weapon parameters like Serpent Spine aren't working properly in configurations.

See attached config.
[noelle_gorou_albedo_fischl.txt](https://github.com/genshinsim/gcsim/files/7798589/noelle_gorou_albedo_fischl.txt)

![image](https://user-images.githubusercontent.com/84653157/147866786-7e0cd02f-dc9a-4f22-ab57-d3a8a5b8e9a9.png)

**Comment by srliao** [comment]
i forgot that the syntax should have been `+params=[stacks=5]`

i added the + since it was optional... but forgot to make it error out otherwise
