### ISSUE TITLE
need to log sara buff expiry

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#137]

**Comment by Tsym-or-Tysm** [comment]
@srliao What is this asking for exactly? There's both a mod and log message that states the expiry frame already.

![image](https://user-images.githubusercontent.com/84653157/149065975-d8dc003f-74fa-4fe6-aa5a-9f7a9189e274.png)

**Comment by srliao** [comment]
I think it was with respect to this: https://discord.com/channels/845087716541595668/884485336657444894/927601209215430716

Probably ok to close though looking at this since we don't ever log expiry
