### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#144]
- [ ] amberbead
- [ ] bloodtaintedgreatsword
- [x] compoundbow
- [ ] darkironsword
- [ ] ebonybow
- [ ] emeraldorb
- [ ] everlastingmoonglow
- [ ] ferrousshadow
- [x] filletblade
- [x] hakushinring
- [ ] halberd
- [x] ironpoint
- [x] katsuragikirinagamasa
- [ ] messenger
- [x] mitternachtswaltz
- [ ] oldmercspal
- [ ] otherworldlystory
- [ ] pocketgrimoire
- [x] polarstar
- [ ] predator
- [ ] quartz
- [ ] ravenbow
- [ ] recurvebow
- [x] seasonedhuntersbow
- [ ] silversword
- [x] slingshot
- [ ] swordofdescension
- [ ] theflagstaff
- [ ] travelershandysword
- [ ] twinnephrite
- [ ] whiteirongreatsword
- [x] whitetassel
- [x] wineandsong
- [x] calamityqueller

**Comment by jordanlovato** [comment]
Auditing the list, The following are in:

* Moonglow/Everlasting Moonglow
* Hakushin Ring
* Ironpoint
* Nagamasa/katsuragikirinagamasa
* huntersbow/seasonedhuntersbow
* slingshot

**Comment by srliao** [comment]
#403 added fillet blade

**Comment by k0l11** [comment]
also missing debateclub and kagotsurubeisshin
