### ISSUE TITLE
adjust Ganyu Q, A4 and C4 logic

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#146]
https://stackoverflow.com/questions/5837572/generate-a-random-point-within-a-circle-uniformly

**Comment by k0l11** [comment]
Some more details: 
- Q pos should probably stay on Player
- every 0.3s: 
  - pos := random point between 0.5m and 9.5m from Q pos
  - potentially overwrite pos: 
    - pos := pos of a randomly selected enemy within radius 10 of Q pos that doesn't have an UnavailableMark on it if it exists
    - if pos was overwritten, then apply UnavailableMark on enemy (lasts for 1.45s, hitlag extendable)
  - drop an icicle on the pos
