### ISSUE TITLE
fischl oz attack interval is off

### ISSUE THREAD

**Issue by NRZ091** [genshinsim/gcsim#1609]
In gcsim, OZ's Thunder element attachment occurs in paragraphs 1  ,  5 (by 4hit)  ,  6 (by 5s)  ,10 (by 4hit)  , and 11 (by 5s).
In the test video, OZ's thunder element attachment occurs in paragraphs 1  ,  5 (by 4hit)  ,  7 (by 5s)  ,  11(by 4hit)
So I guess OZ's sixth attack didn't actually attach because of the timer refresh

In the test video:
[test.zip](https://github.com/genshinsim/gcsim/files/12269804/test.zip)

In gcsim:
https://gcsim.app/sh/fn6q9JjPCqHd

**Comment by k0l11** [comment]
The ICD is not wrong, however the interval between oz hits is off because current assumption is 60f always, but it's clearly shorter ingame. Looking like first oz hit should be 50f from gcsim's oz spawn and every subsequent hit 58f after, but I will record frames for that later.

**Comment by NRZ091** [comment]
Ok. Thanks for your hard work

**Comment by NRZ091** [comment]
In a 4hit/5s counter, will the timer refresh be triggered when the time equals 5s?
Probably not?

**Comment by k0l11** [comment]
Yes, it should

**Comment by NRZ091** [comment]
Because I asked a few people, and they said that when the time is equal to 5s it doesn't trigger the timer to refresh
And they gave me some references

![image](https://github.com/genshinsim/gcsim/assets/108729837/29dc20e4-86b0-4e3e-be5e-ab87f841568d)
from：tesiacoil
link： https://bbs.nga.cn/read.php?tid=31217959

![image](https://github.com/genshinsim/gcsim/assets/108729837/fafafd48-48d1-43f2-8dc7-9c68d52df52d)
from：KQM TCL
link： https://library.keqingmains.com/combat-mechanics/internal-cooldown#advanced-overview

**Comment by k0l11** [comment]
Please clarify what your point is, because I don't get it. After 5s or however long the time "rule" is, the hit rule is reset and there will be an elemental application on the hit.

**Comment by NRZ091** [comment]
I'm sorry, I may not have been very accurate

I mean that
Based on the above
when Time interval≤5s：
It will not be refreshed by the timer

when Time interval>5s：
It will be refreshed by the timer

**Comment by k0l11** [comment]
Will be fixed to be >t instead of >t-2 here: https://github.com/genshinsim/gcsim/pull/1616.

**Comment by NRZ091** [comment]
Okey.
And then now is OZ's attack interval 59 frames or 60 frames?

**Comment by k0l11** [comment]
See https://github.com/genshinsim/gcsim/pull/1615.

**Comment by NRZ091** [comment]
Okey.

**Comment by NRZ091** [comment]
Emmmm....
First of all, I'm sorry.
I showed #1615 to the guy I asked earlier
Then he told me that oz's attack interval is 1s in Dim
![494daa2e4588b6b5723ead53bfafda4](https://github.com/genshinsim/gcsim/assets/108729837/f76226cd-6292-47f5-88b3-f196ff48d397)

**Comment by k0l11** [comment]
Reopen if there is something I missed.

**Comment by NRZ091** [comment]
OK.I get it now
But I think there should be no problems for the time being
If I find other problems, I will open or submit a review issue again
Thank you for your hard work.

**Comment by k0l11** [comment]
I also thank you for finding gaps/bugs.
