### ISSUE TITLE
bow character require short aim shot for proccing headshot

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#174]
need to find out the frames for this

**Comment by Tsym-or-Tysm** [comment]
Have frames here. Just need to figure out syntax for it

https://docs.google.com/spreadsheets/d/1e8to2PGZgpykGsi2G-mkAWiY2OSLUBgUkWfM5N4B6fk/edit#gid=0

**Comment by srliao** [comment]
Got permission from BowTae#0141 to use this

![image](https://user-images.githubusercontent.com/906239/152356104-172afb1c-a9a4-4945-8643-245d95c3b8ee.png)

**Comment by k0l11** [comment]
updated sheet:
https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing

**Comment by k0l11** [comment]
stuck in limbo because of syntax problems (#772)

**Comment by k0l11** [comment]
done in #1980
