### ISSUE TITLE
Set CD sometimes triggers CD extremely later even though it is being called immediately

### ISSUE THREAD

**Issue by HanSeoulOh** [genshinsim/gcsim#177]
https://viewer.gcsim.app/share/nUxpJh68IUfPkVWXh4X2Q

Diona burst CD doesn't trigger until f65 allow Diona to burst twice

**Comment by HanSeoulOh** [comment]
I was not able to reproduce this bug when running the config on latest build

**Comment by HanSeoulOh** [comment]
Tsym thinks it's because of the frames..... WIP

**Comment by srliao** [comment]
should fixed in #183 

closing for now until someone else complains
