### ISSUE TITLE
Improve Parser Errors

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#188]
Need to try to make parser errors better - sometimes they're very cryptic. We should at least return the correct line number and show the line that's causing the error in the message, which should be fast.

Slightly separate but related, we need to make a system so that parser errors out when receiving unexpected parameters to an item, and perhaps even helpfully provides a list of valid parameters (maybe too optimistic).

**Comment by Tsym-or-Tysm** [comment]
We should look for calc mode commands (restart/wait) and provide a better error message if they're not run in calc mode. Right now the sim just says like
`unknown action block type`

**Comment by srliao** [comment]
should be ok to close. `next` should handle this a bit better
