### ISSUE TITLE
Add low plunge for Xiao

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#192]
Low plunges are easier to do than high plunges, which may be useful to sim. Credit to nyktós#4458 for raising.

**Comment by HanSeoulOh** [comment]
srl thinks this one is not that trivial so removing it from good first issues

**Comment by k0l11** [comment]
related to #209 
I've recorded Low Plunge cancels so maybe Low Plunge can be implemented after the frames in my Xiao video get counted?
