### ISSUE TITLE
Dehya Skill Double cast cooldown issue

### ISSUE THREAD

**Issue by shjeauxwn** [genshinsim/gcsim#1977]
It appears that if you start a rotation by casting Dehya's skill twice, the initial cast immediately followed by ranging flame, beyond the first rotation the sim will wait for the full skill cooldown between the first cast and ranging flame. The skill is definitely off cooldown, because it will cast the initial skill again, but it doesn't seem to recognize that ranging flame can be cast immediately after again. Ranging flame should always be able to be cast if the initial skill has been cast.

I saw that there were some fixes to Dehya quite recently, one of which seems to address this issue. However I am still experiencing this after updating to the newest version. Also tried using a different browser to be really sure there wasn't anything old from the cache hanging around.

Here is a config that should demonstrate the issue:

https://gcsim.app/sh/8GhMJPcnmPR8

```
dehya char lvl=90/90 cons=2 talent=10,10,10;
dehya add weapon="beaconofthereedsea" refine=1 lvl=90/90;
dehya add set="emblemofseveredfate" count=4;
dehya add stats def=42 hp=4989 hp%=0.047 atk=311 atk%=0.298 er=0.7310000000000001 em=110 cr=0.45899999999999996 cd=1.291 pyro%=0.466;

kazuha char lvl=90/90 cons=0 talent=8,8,8;
kazuha add weapon="favoniussword" refine=5 lvl=90/90;
kazuha add set="viridescentvenerer" count=4;
kazuha add stats def%=0.051 def=59 hp=6364 hp%=0.14 atk=363 er=0.32999999999999996 em=674.5 cr=0.319 cd=0.187;

bennett char lvl=90/90 cons=6 talent=2,6,10;
bennett add weapon="aquilafavonia" refine=1 lvl=90/90;
bennett add set="noblesseoblige" count=4;
bennett add stats def%=0.139 def=63 hp=5228 atk=365 atk%=0.24 er=1.01 em=68 cr=0.548 cd=0.498 pyro%=0.466;

mona char lvl=80/80 cons=4 talent=4,6,8;
mona add weapon="favoniuscodex" refine=5 lvl=90/90;
mona add set="emblemofseveredfate" count=4;
mona add stats def%=0.057999999999999996 def=19 hp=5766 hp%=0.053 atk=311 atk%=0.158 er=0.66 em=129 cr=0.54 cd=0.956 hydro%=0.466;

options iteration=1000 swap_delay=12;

								
target lvl=100 hp=9999999 resist=.1 pos=0,2.4 radius=2;
energy every interval=480,720 amount=1;
hurt every interval=480,720 amount=1,300 element=physical;

active dehya;

for let i = 0; i < 4; i = i + 1 {
    dehya skill, skill;
    kazuha skill, high_plunge;
    bennett skill, burst;
    mona burst, skill;
    dehya burst, attack:11;
    kazuha skill, high_plunge, burst;
    mona attack:3;
    bennett attack, skill;
    dehya attack:2;
}
```

**Comment by k0l11** [comment]
the fix is now live in web (commenting in case you are not in our discord)
