### ISSUE TITLE
Add Yoimiya Aimed Attack (Need Frame Data)

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#207]
Yoimiya aimed attack is currently not implemented, but there is no frame data for it in KQM library, so we can't really add it until that's available.

https://library.keqingmains.com/characters/pyro/yoimiya

**Comment by srliao** [comment]
should be part of #209

**Comment by srliao** [comment]
https://docs.google.com/spreadsheets/d/1tmLrAF_kTc0GGBq2Y6rze2NyYpogw9aW0NJlNQuAlng/edit#gid=1519011669 from Light
