### ISSUE TITLE
Comprehensive Frame Update

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#209]
## Introduction

Purpose of this ticket is to keep track the recount of all characters in accordance with gcsim's frame framework, which differs slightly from existing count in that we require recovery frame and cancellable frame for all possible combination of actions.

We're looking for help from everyone with both recording and frame counting. If you are able to contribute please leave a comment below. Looking for help both in terms of just providing raw footage as well as performing the count. It'd help us greatly if you can provide help with either or (or both should you desire).

## Recording requirement

- Record at consistent 60fps 720p minimum
- For each character, record all possible combinations of various ability, including but not limited to
  - string of normal attacks i.e. N1 -> N5 -> N1 (usually done by button mashing)
  - cancelling of each normal attack with charge attack i.e. N1 -> CA, N2 -> CA, etc...
  - cancelling of skill with every other possible action i.e. NA, CA, skill, burst, dash, jump swap
  - cancelling of burst with every other possible action i.e. NA, CA, skill, burst, dash, jump swap
  - cancelling of CA with every other possible action i.e. NA, CA, skill, burst, dash, jump swap
  - any other combinations for character with special abilities i.e. skill hold, etc...
- We'll need 3 trials of every combination to help average out any recording error
- All footage should be done vs empty air (not hitting trees) as sim is using no hitlag frames
- Footage should start clearly from standing/rest position and end at standing/rest position to avoid cutting off any part of the animation
- Footage should not be obstructed in anyways by trees, rocks, enemies, etc... 

## Frame count requirements

```
NX/CA hitmark / NX/CA hitmark when infused:
start frame: start of the animation of NX
end frame: hitmark registered on target = 2 frames after the frame where the yellow mark first appears 

E hitmark / Q hitmark / D hitmark (only if special dash):
start frame: first frame the buttons bottom right grey out
end frame: frame the element gets applied (Pyro/Hydro/Electro/Dendro?/Cryo) / the first frame the Swirl (Anemo) or Crystallize (Geo) text appears

NX -> NY:
start frame: start of the animation of NX
end frame: start of the animation of NY

NX -> CA:
start frame: start of the animation of NX
end frame: first frame the buttons bottom right grey out

CA/E/Q -> E/Q / D -> E/Q (only if special dash):
start frame: first frame the buttons bottom right grey out
end frame: first frame the buttons bottom right grey out for the next action

CA/E/Q -> N1/D/J / D -> N1/D (only if special dash):
start frame: first frame the buttons bottom right grey out
end frame: start of the animation of N1/D/J

CA/E/Q -> Swap  / D -> Swap (only if special dash):
start frame: first frame the buttons bottom right grey out
end frame: first frame the team names aren't grey'd out anymore

frames = end frame - start frame
```

## Recount Status

| character | link to sheet | videos | issue/pr | status |
| --- | --- | --- | --- | --- |
| albedo | [sheet](https://docs.google.com/spreadsheets/d/1WIejtwUZpZ2lqTNlK2_6cJPoDe0PUmCL6QKB05m_AQQ/edit?usp=sharing) | [video](https://youtu.be/BYr-3R-XpfE) | #671 | |
| aloy | [sheet](https://docs.google.com/spreadsheets/d/11uyES6x6UFGm2bqcsY4dPSqLgsELrdkPv145NmMwTmc/edit?usp=sharing) | [video](https://youtu.be/mGnzKSsvq9s) | #672 | |
| amber | [sheet](https://docs.google.com/spreadsheets/d/1XDS-RP7G7-htZ4PP9A5SXPbg7Gy-Laksp4oXwObNgf8/edit?usp=sharing) | [video](https://youtu.be/UrChJbc4juc) | #673 | |
| ayaka | [sheet](https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing) | [video](https://youtu.be/ulTSQRrR4n8) | #425 | |
| ayato | [sheet](https://docs.google.com/spreadsheets/d/1VL6nQvehIj8wTFC6ACC88p3i8lGUZnZV8Lx0G1dZp88/edit?usp=sharing) | [video](https://youtu.be/NNBdbP4Rn28) | #458 | |
| barbara | [sheet](https://docs.google.com/spreadsheets/d/1R_OywCjjSW8PeYPPniBLVnoTZ8uQ2L_GLKYmQvFTHV0/edit?usp=sharing) | [video](https://youtu.be/ZlKREU4NZPA) | #676 | |
| beidou | [sheet](https://docs.google.com/spreadsheets/d/1r8fwU2wMBbZsy5fqqSSf8aLvX8aFvJCvaDD8P3Lr2sI/edit?usp=sharing) | [video](https://youtu.be/mCDHSI1JhuI) | #527 | |
| bennett | [sheet](https://docs.google.com/spreadsheets/d/1xjUpc3yUcpqaioep250lfxlpK-feDbdrBmD0TuvBcoA/edit?usp=sharing) | [video](https://youtu.be/d6X6yF4ffXM) | #502 | |
| chongyun | [sheet](https://docs.google.com/spreadsheets/d/13TsDRmuHCrXBKlka-huhKt1xtjNHhLEZIuJJzj1OQvg/edit?usp=sharing) | [video](https://youtu.be/BjgV0LkDUpA) | #674 | |
| diluc | [sheet](https://docs.google.com/spreadsheets/d/1p0blrnuM7JvwU2QMdZdLayYqP3-7OMDgYC6GDQNn_QU/edit#gid=547671271) | [video](https://youtu.be/KsBKdqCPFj8) | #510 | |
| diona | [sheet](https://docs.google.com/spreadsheets/d/178Y92g19FlBIb1hIPHKvjByk_NztZ7854pjkkt4fEV4/edit?usp=sharing) | [video](https://youtu.be/iPphkHE5U5g) | #675 | |
| eula | [sheet](https://docs.google.com/spreadsheets/d/1NCDFtvqFdXlVRd_0eH2tPw7xMD50AxUCvbWDh1XGhEw/edit) | [video](https://youtu.be/Bj7C6zs4Xsc) | #477 | |
| fischl | [sheet](https://docs.google.com/spreadsheets/d/1Pbp9BY1HZIs_iPJdkR3B7WjLMO9iIjWP8tM7NNnp0bU/edit?usp=sharing) | [video](https://youtu.be/FCgs75yM18Q) | #503 | |
| ganyu | [sheet](https://docs.google.com/spreadsheets/d/1PDHCZKh-7eWpbE1b0OyQUCzSPHcViYZ22EDEItjiU7Y/edit?usp=sharing) | [video](https://youtu.be/ROvivlCUR3s) | #448 | |
| gorou | [sheet](https://docs.google.com/spreadsheets/d/15eKpg9ii86ufny24TEZgzWT0xQbzmIfMUCA2fktuaB4/edit?usp=sharing) | [video](https://youtu.be/pOJnyO91pQ8) | #677 | |
| heizou | [sheet](https://docs.google.com/spreadsheets/d/1SsXniQztelJOBWMYPT-w6wygSFkduWhu2OAVC9IUbbA/edit?usp=sharing) | [video](https://youtu.be/CTIsFo_3j2I) | #640 | |
| hutao | [sheet](https://docs.google.com/spreadsheets/d/1KR_FMtupIbLEhWRGww2N2UKEJG3hy5mWJIez8S6EZ2w/edit?usp=sharing) | [video](https://youtu.be/9IPwipyFu4A) | #665 | |
| itto | [sheet](https://docs.google.com/spreadsheets/d/13ad3uH2DazxotwjQE6qvWRfcQJpmhkxN4nsbc3vUx78/edit?usp=sharing) | [video](https://youtu.be/1slUOvTY9c0) | #661 | |
| jean | [sheet](https://docs.google.com/spreadsheets/d/1KQB8VOEyaCsRa3QulF-gAq3a1CxsqiauTNYuK2_paMY/edit?usp=sharing) | [video](https://youtu.be/HJrJkYgsg84) | #460 | |
| kaeya | [sheet](https://docs.google.com/spreadsheets/d/11f_FxKhXFpL4EHSfFHPPjhXJvVOTi-FP_R6cqaZ9dwo/edit?usp=sharing) | [video](https://youtu.be/RvgMyM9f3Gk) | #678 | |
| kazuha | [sheet](https://docs.google.com/spreadsheets/d/1uEbP13O548-w_nGxFPGsf5jqj1qGD3pqFZ_AiV4w3ww/edit?usp=sharing) | [video](https://youtu.be/xwdec3mg6rM) | d10b8e0 | |
| keqing | [sheet](https://docs.google.com/spreadsheets/d/1GAeBzMr0XX89azZhpbjEqPfehgruwI3__GlfEgQ1VvA/edit#gid=775340159) | [video](https://youtu.be/kI6N3Mn5BQY) | #504 | |
| klee | [sheet](https://docs.google.com/spreadsheets/d/1cRHRn2iR8knyzcioUGGoMFNZgaNJQdlpkUqjeIPowCM/edit?usp=sharing) | [video](https://youtu.be/jDQDx1hhzkc) | #666 | |
| kokomi | [sheet](https://docs.google.com/spreadsheets/d/1j3Hzo25qSqo-ZbQBiBqcejR1aa91igSVTxH1xoKYrfc/edit) | [video](https://youtu.be/Rp8-WwtFxSY) | #528 | |
| kuki | [sheet](https://docs.google.com/spreadsheets/d/1cXejpod69F6HReq6jztxEvlpVzSGKssz5NNHIzqY4QY/edit?usp=sharing) | [video](https://youtu.be/kbdvX4Oy-u0) | #679 | |
| lisa | [sheet](https://docs.google.com/spreadsheets/d/1KRt6I_c5qeUQVXcHv7ZOZKdqjn4Z_VN1OyVFvhDumOc/edit?usp=sharing) | [video](https://youtu.be/f58tVgt3OYw) | #552 | |
| mona | [sheet](https://docs.google.com/spreadsheets/d/1fCdmkNZ6vXmqiOmk6s0Q8AQFzOQt_UjltspbMyDrx4A/edit?usp=sharing) | [video](https://youtu.be/KfjCdGrh5Dk) | #698 | |
| ningguang | [sheet](https://docs.google.com/spreadsheets/d/12y2e2JkN55UOpbMeTpx1EmqqN9zdfPf3jLLpo9YKxnE/edit?usp=sharing) | [video](https://youtu.be/r_NAO1Lld3Q) | #687  | |
| noelle | [sheet](https://docs.google.com/spreadsheets/d/1fpJmJ7SylDkrb0-ghuAnUc977Lf6yH-uWpOmyvazFNM/edit#gid=0) | [video](https://youtu.be/yAgWbb-jSRk) | #447 | |
| qiqi | [sheet](https://docs.google.com/spreadsheets/d/1uS_n16mlfdfzjBiVG3w6TmR9H7YqSSFOoyox_9bn-Kk/edit?usp=sharing) | [video](https://youtu.be/56yh-6WqN-I) | #680 | |
| raiden | [sheet](https://docs.google.com/spreadsheets/d/1ayeS2Yp32dbdVR-xqSyIeSk7CUDuIFSO6A8XrRCRNgY/edit?usp=sharing) | [video](https://youtu.be/70hVIt1_92Y) | #478 | |
| razor | [sheet](https://docs.google.com/spreadsheets/d/1Rceie6ATwNDSbnmIIKgZa1cVtXlBZE6earpJb42SHAM/edit?usp=sharing) | [video](https://youtu.be/CUXnqF1S2ps) | #688 | |
| rosaria | [sheet](https://docs.google.com/spreadsheets/d/1buBVBvlgfNcRA09XA3BLm-oA7hpCVRYkGt_7kPBYJu0/edit?usp=sharing) | [video](https://youtu.be/_FVJTwjKW4A) | #482 | |
| sara | [sheet](https://docs.google.com/spreadsheets/d/1B29Zceb_pl8FYfHtIrZeMttZtovmwE8tHEZud_kkbmo/edit?usp=sharing) | [video](https://youtu.be/omTcYawTD8U) | #690 | |
| sayu | [sheet](https://docs.google.com/spreadsheets/d/1vLH6ZiAhb7G-f5ecYy-sPLoCdouA5krMixtgh9ITX2Q/edit?usp=sharing) | [video](https://youtu.be/w7YDOFDuVC0) | #704 | |
| shenhe | [sheet](https://docs.google.com/spreadsheets/d/1CeCbNYTXozBDeeRerGJFLWwsKrKz3K3-PydNSBATx8E/edit) | [video](https://youtu.be/27cpC8A_elw) | #689 | |
| sucrose | [sheet](https://docs.google.com/spreadsheets/d/1qHFGd5xt2MNBCIw7WK78lwv2Az98vLz8CRILU8piugo/edit?usp=sharing) | [video](https://youtu.be/qFTyVL1cA4w) | #463 | |
| tartaglia | [sheet](https://docs.google.com/spreadsheets/d/1TDAItxWT_p76Z84EMpk2oIAN2etTWR0DiubllnWBnbc/edit?usp=sharing) | [video](https://youtu.be/FSE7NhQSbHE) | #667 | |
| thoma | [sheet](https://docs.google.com/spreadsheets/d/1QtllZ_QKQIJNGnD4FILZCB307aA8YtDfpG6pcYndl5E/edit?usp=sharing) | [video](https://youtu.be/wnOvlhq8us4) | #684 | |
| traveleranemo | | | #734 | |
| travelerelectro | | | #734 | |
| travelergeo | | | #734 | |
| venti | [sheet](https://docs.google.com/spreadsheets/d/1wjNpI530VwWX8PtmAA7ZZex5FurVpItfu6jmRQsMcaw/edit?usp=sharing) | [video](https://youtu.be/6SNc67MnDz8) | #449 | |
| xiangling | [sheet](https://docs.google.com/spreadsheets/d/1tWMpn1M34w0rCutUQ5cem28fIVoFVp7YjOXtIm2Rvow/edit?usp=sharing) | [video](https://youtu.be/ibZji4bP7Gs) | #524 | |
| xiao | [sheet](https://docs.google.com/spreadsheets/d/1WHJy9UjCQY0AO32yluJMhX_ecGO1KGb6SjbOZt9VJDg/edit#gid=775340159) | [video](https://youtu.be/oadNODbooZQ) | #511 | |
| xingqiu | [sheet](https://docs.google.com/spreadsheets/d/1eJDOj2mI3tFSM7ii6hn3E9GLtS6ah5GwCISDyb2i304/edit?usp=sharing) | [video](https://youtu.be/SqKyJcmZvHY) | #444 | |
| xinyan | [sheet](https://docs.google.com/spreadsheets/d/1Wz7gtnavp5pzNjSFidi0EFluZ4E8CoaogvzOXSEF3-E/edit?usp=sharing) | [video](https://youtu.be/PT7BQuZAVTE) | #691 | |
| yaemiko | [sheet](https://docs.google.com/spreadsheets/d/1G8_pp_NFtM1wteo_xRZaG-lTcS3NZ1vADVmjFFp_SOk/edit?usp=sharing) | [video](https://youtu.be/UUcbZDh4oIA) | #692 | |
| yanfei | [sheet](https://docs.google.com/spreadsheets/d/1NslqbafUoW4rhl1D2oVeSsn0SXfvAwnxAlIlwvKY_5Q/edit?usp=sharing) | [video](https://youtu.be/O43Ws1bgyXY) | #693 | |
| yelan | [sheet](https://docs.google.com/spreadsheets/d/1k4f8EkgneV_588EpJlDavx_0zyFi5ZiWd0HdUV6wx38/edit?usp=sharing) | [video](https://youtu.be/4WpZhbvEktU) | srliao/gcsim#5 | |
| yoimiya | [sheet](https://docs.google.com/spreadsheets/d/1DYYiGSNeFekVt3eQQC_MujkLCd_8rgPIIlpPNvwHKTA/edit?usp=sharing) | [video](https://youtu.be/UNo3Q-DPmbM) | #529 | |
| yunjin | [sheet](https://docs.google.com/spreadsheets/d/1rDQZ8TJd6JAzD3C6pg_JZrgkYr-LIp36mmXE8XVMj4s/edit?usp=sharing) | [video](https://youtu.be/dIlxs5zi1e0) | #695 | |
| zhongli | [sheet](https://docs.google.com/spreadsheets/d/1NPOothWseChb-OzOHQqunBdi-M3udmQPqPop0kf7H-w/edit?usp=sharing) | [video](https://youtu.be/2TMxz446akc) | #508 | |

## Original issue:

This issue was hijacked to track the rework. Original comment from Tsym as follows:

This is a global issue to track frame data issues/fixes. After some investigation, the primary set of issues relate to how KQM frames are measured:

- For NA/CA frames, KQM frames are usually until hitmark (or from hitmark to hitmark). Currently, the frames that we have loaded are therefore usually ok until the last NA/CA in the sequence, when there will be no ending animation. However practically this is not a significant concern because most NA/CA chains in the game are cancelled in some way (mostly through dashes or jumps).
  - The one exception here are aimed shots, whose frames in KQM are from start until shot release. Since aimed shots are usually not dash/jump cancelled, these require special attention.
- For skill/bursts that do involve a hit, KQM frames are until the hitmark, so they will tend to run fast.
- For skill/burst frames that do not involve a hit during the main animation (e.g., Barbara, Venti), KQM frames are until the end of the animation and so are usually decently accurate.

The sim running a bit fast is therefore partially a result of skill/bursts with hits having missing ending animation frame data. This will however take a significant amount of time to fix.

The current proposed plug solution is to add a delay parameter so users can add a custom delay to the end of animations. See #206

**Comment by k0l11** [comment]
Ayaka cancel frames to count:
https://youtu.be/ulTSQRrR4n8

**Comment by kurt22i** [comment]
https://docs.google.com/spreadsheets/d/1BdWsPgnZFJ2xFmKgYevvBXYQeDqOLaPpL_VsFzjjiiI/edit?usp=sharing
xingqiu frames sheet. currently only 1 trial each (in future counts I will do 3) and not all combos tested, let me know how much more needs to be done before opening a pr.

**Comment by srliao** [comment]
> https://docs.google.com/spreadsheets/d/1BdWsPgnZFJ2xFmKgYevvBXYQeDqOLaPpL_VsFzjjiiI/edit?usp=sharing xingqiu frames sheet. currently only 1 trial each (in future counts I will do 3) and not all combos tested, let me know how much more needs to be done before opening a pr.
> 
> more chars: Bennett: https://docs.google.com/spreadsheets/d/1wzaBId5I0wxqlikpdZZlXaXRDuCykbdn4izbK__OHss/edit?usp=sharing Xiangling: https://docs.google.com/spreadsheets/d/1lWpwV9RVKsk9X3ghww7ooujxJsonfqC9krWzrXffv3c/edit?usp=sharing

ideally we get to 3 samples but I'll start coding these in as soon as I get the chance to

**Comment by kurt22i** [comment]
used koli's video to implement ayaka frames [here](https://github.com/genshinsim/gcsim/pull/425), macro footage really does make this process a lot easier

**Comment by srliao** [comment]
#447 updates noelle but missing:

attack -> charge
attack -> walk
charge -> x

**Comment by srliao** [comment]
all done (for now until tomorrow) :) this is also tracked in docs as well
