### ISSUE TITLE
any plan to implement noelle charge and razor plunge?

### ISSUE THREAD

**Issue by leepc12** [genshinsim/gcsim#2127]
I'm trying to implement a whirlwind Noelle and tried `noelle charge;` but got the following error:
![image](https://github.com/genshinsim/gcsim/assets/8625660/34f39e4b-5e14-4815-bab0-2af15c2c20b3)

and similar thing for `razor jump, high_plunge;`
![image](https://github.com/genshinsim/gcsim/assets/8625660/339ee6fa-4284-437f-86ee-91e92ec316a9)

Is there any plan to implement `noelle charge` and `razor high_plunge`?

**Comment by k0l11** [comment]
Probably not in the near future for both, both of these are currently already tracked on Discord https://discord.com/channels/845087716541595668/1219677574125584425 and https://discord.com/channels/845087716541595668/1218373005902745603 so closing this one.
