### ISSUE TITLE
[proposal] Remove simulation option parsing from parser and move to executable code instead

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#219]
Currently, simulation options such as debug mode, number of iterations and number of workers are parsed by the parser. I'm proposing that instead of parsing these options using the parser, they are handled independent from the parser.

For example, in the current code we have:

```go
	parser := parse.New("single", data.String())
	cfg, opts, err := parser.Parse()

	opts.ERCalcMode = o.ercalc

	if err != nil {
		log.Println(err)
		os.Exit(1)
	}

	if o.i > 0 {
		opts.Iteration = o.i
	}
	if o.w > 0 {
		opts.Workers = o.w
	}
	if o.debug {
		opts.Debug = o.debug
	}
	if o.seconds > 0 {
		opts.Duration = o.seconds
	}
	if o.detailed {
		opts.LogDetails = true
	}
```

Here the command line tool is parsing the config file, pulling out the options, and then override then if the related command line args are present. Instead, I'm proposing that the options are parsed directly by the command line tool via a simple RegEx (and then subsequently stripped out so not to cause parser errors). This is more consistent with how the back end is handled as the options are ignored as you can see from the Run code signature

```go
func Run(src string, cfg core.Config, opt core.RunOpt, cust ...func(*Simulation) error) (Result, error) {
```

The sim relies on the `opt core.RunOpt`.

This way, the parser is kept cleanly to only parsing what is relevant for each iteration. The `defaults` syntax can be more consistent this way as well as everything pertaining to each iteration (such as calc mode, er mode, etc...) can be kept together. Logically this makes more sense too as each run don't really need to know how many total iterations, or if there's +1 for debug run or not.

I personally don't see any downsides this but want to get some thoughts on this to see if I missed anything? @Tsym-or-Tysm let me know if I missed anything?

**Comment by Tsym-or-Tysm** [comment]
Discussed on Discord and I think we're good to proceed with this since we're mostly just reorganizing where the options handling takes place. Proposal here is more so that options handling will be moved outside of the parser, but can still exist within the config.

**Comment by srliao** [comment]
Dropping this as I realized that half of our performance issue was due to rerunning parser every iteration... doh
