### ISSUE TITLE
Ayaka appears to not be getting full Mistsplitter stacks 

### ISSUE THREAD

**Issue by connor-rk800** [genshinsim/gcsim#230]
[ayakatest.gz](https://github.com/genshinsim/gcsim/files/8005313/ayakatest.gz)

at 11.37s Ayaka uses a normal attack into burst which should be 3 stacks.

however the snapshot mods on Soumetsu says mistsplitter is giving 28% cryo when it should be 40% (12% passive + 28% stacks).

also at 17.62s, Ayaka's N2 now says 36% cryo in snapshot mods, which is unusual as no combination of mistsplitter stacks should result in 36%.

**Comment by srliao** [comment]
should be fixed in #232
