### ISSUE TITLE
Add Walk Cancels Consistently

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#239]
See title.

Currently only Klee has a manual exception for this, but technically this can be done with every character.

Currently mostly only relevant for catalyst attackers... Not sure if there's any instance of this happening often for non-catalysts since they mostly use dashes/jumps.

**Comment by srliao** [comment]
We can certainly add walk in as an action. Question becomes though what the frame count would be...

**Comment by soloxcx** [comment]
I poked around in KQM and was led to this ticket that attempted to explore the mysteries of walk cancels until it went untouched for a month and archived https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/923418129219092520/931977067698995231/transcript-catalyst-walk-cancel-frames.html

**Comment by Tsym-or-Tysm** [comment]
> We can certainly add walk in as an action. Question becomes though what the frame count would be...

@srliao I checked a few videos and I think walks should by default be 1 frame given how both Klee and Ningguang's NA walk cancels work, so I added it in #258 

If someone wants a longer walk then they can use the "delay" parameter that we'll be adding to all actions or something?
