### ISSUE TITLE
Rework results aggregation / additional data collection

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#241]
Issue to track reworking results aggregation including:

- Putting in a dataframe
- Potentially tracking additional statistics

Some suggestions thus far:

- Average buff uptime
- Number of reactions triggered by each ability (related to reaction ownership)

**Comment by srliao** [comment]
![image](https://user-images.githubusercontent.com/906239/153319947-c0ae225e-9bf0-4680-a47c-953f73ae9603.png)
Sample output from wow simc. I can see Crit % being useful.

Also a good point from Zephyr (https://discord.com/channels/845087716541595668/884485336657444894/941143691425349682) is that showing absolute max hit can be very valuable.

**Comment by k0l11** [comment]
@unleashurgeek is this done via #1359?
