### ISSUE TITLE
Eula frames rework

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#247]
TWICE#9958 from KQM and EulaMains has given the eula frame data that they use and how it compares to the KQM TCL ([discord message link in kqm](https://discord.com/channels/763583452762734592/763610791839924224/941857536527720468), [imgur link](https://imgur.com/po0ylpm))

**Comment by k0l11** [comment]
related to #209

**Comment by k0l11** [comment]
this will probably get closed by #477
