### ISSUE TITLE
Implement System to Allow for Setting Custom Animation Delays between Actions

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#256]
This has been discussed previously, but I don't think we had a dedicated issue for it.

Basically the idea is that there are certain cancels that can be done faster than other actions, such as Venti E -> Q, which the current system doesn't account for properly.

srl already has a framework for this ready, with relies on the `ActionInterruptableDelay` function, but it is currently unimplemented for all characters, and whose implementation is tied to #119.

Once the system is in place, this issue will be used to track progress on updating cancellable frames for certain major interactions. List of interactions TBD...

**Comment by srliao** [comment]
this is now tracked in #209 

probably should have hijacked this issue instead of that one...
