### ISSUE TITLE
Adjust Burst Cooldown Frames to Match New Data

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#260]
Data available in this sheet: https://docs.google.com/spreadsheets/d/1iLUT8Tafwih3RZbNlA59w6-x5NQdgPvsMc86b7W92DQ/edit#gid=0

From this ticket in KQM: https://discord.com/channels/763583452762734592/934497970991296613/934498290848911541

**Comment by srliao** [comment]
should be done
