### ISSUE TITLE
Anemo Ability Elemental Absorptions Are All Incorrect And Need Control Parameters

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#262]
They apparently pick up auras in a way too big radius, so they often incorrectly pick up self-elements, such as Sucrose Q.

Furthermore, due to some absorptions being fairly unreliable in game (e.g., Sucrose), we need to add a parameter to some abilities to control whether they pick up an absorption or not (or even control the exact element absorbed?). The biggest factor for this currently is probably just Sucrose Q?

**Comment by jordanlovato** [comment]
https://github.com/genshinsim/gcsim/pull/427 adds a collision check for sucrose (and several other anemo)

**Comment by srliao** [comment]
fixed in #427 

will open separate issue for forced infusion if enough requests
