### ISSUE TITLE
Amber Aimed Shot at Bunny Crashes Sim

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#264]
From Hatsuharufag:

https://discord.com/channels/845087716541595668/869210750596554772/935192461897269248

![image](https://user-images.githubusercontent.com/84653157/153785737-ec474631-7142-4620-bd4c-c4a2b688d007.png)

**Comment by srliao** [comment]
I can't reproduce.. should we close? @Tsym-or-Tysm 

```
options debug=true iteration=1 duration=90 workers=24 mode=sl;

amber char lvl=90/90 cons=5 talent=9,9,9; 
amber add weapon="amosbow" refine=1 lvl=90/90;

##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

active amber;

amber skill;
wait 40;
amber aim[bunny=1];
amber skill;
```

![image](https://user-images.githubusercontent.com/906239/155643119-ef7402bf-e1de-4c57-9593-92c947030b1e.png)

**Comment by Tsym-or-Tysm** [comment]
Tried for a bit and also can't reproduce - we can revisit if it becomes an issue again later.
