### ISSUE TITLE
Add Global Delays for Each Action Type, and Add Default Setting for "Human Frames"

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#267]
Related to the frames/particles issue, I did some frame counts, and my sense is that while we could fine tune a few of these frame counts, the overall problem is not really about particle timing or the ending animation cancels, but rather that people unconsciously do all these micro-waits in game, and then expect the sim to mostly just work out of the box, and bounce off somewhat hard from the sim when it doesn't.

I think that aside from the per-each action delay stuff, we should probably also add in a setting for global delays across each type of action, that kind of simulate something closer to human play, and then make that our "human default" settings because there's no way we can do an individualized setting for each character. So something like the below:
```
defaults swap_delay=8 burst_delay=20 skill_delay=10 charge_delay=8;

rosaria skill[delay=20];
```
Would set swap delay to 8, and would add the number of frames to all usages for each action in the sim. So for example each skill usage would have 10 frames of ending animation by default, and then Rosaria E would have another 20 frames (total of 30 frames of delay).

We can then just create some reasonable global delays based on a few videos and add them as a global option like so:
```
defaults frame_counts="human";
```
which could be treated as equivalent to the above `defaults` statement or something. That will probably catch like 90% of all use cases, and then the remaining people who need really fine grained control (mostly Hu Tao I'm guessing since her frame timing is really tight) can add in manual waits.

Related to #171 and #209.

**Comment by srliao** [comment]
#352 merged into main
