### ISSUE TITLE
C1 Childe incorrect cooldown calculation

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#270]
[childetest.gz](https://github.com/genshinsim/gcsim/files/8064309/childetest.gz)

In here, C1 Childe is in melee stance for 10.48 seconds. His cooldown is then supposed to be `(10.48 * .8) + 6` or 14.384s. However the sim is doing `(10.48 + 6) * .8` or 13.184s. 

I confirmed this is the Childe Main's discord. They use a [melee duration calculator](https://docs.google.com/spreadsheets/d/1tZuAo96gZiweir1KExSbLCQAnr5DGwpgYu3y2q6uFfA/edit#gid=0). Note the cells D23, J23, etc. show that the first formula is used.

**Comment by Tsym-or-Tysm** [comment]
Childe melee cooldown is actually stepwise - do we know whether this should this only be a special exception for the 2 parts of the function that have an additive component?

See: https://genshin-impact.fandom.com/wiki/Foul_Legacy:_Raging_Tide

**Comment by soloxcx** [comment]
Sorry about this one, think I was misinformed.

I have C1 Childe and gave it a test myself https://youtu.be/7upaxLUZ70M. Stayed in melee for almost exactly 11 seconds and got a 13.6 cooldown, which follows the second formula of `(11 + 6) * .8`.

**Comment by soloxcx** [comment]
Okay yeah it's straight up 20% reduction as already implemented. That calculator is just wack

**Comment by Tsym-or-Tysm** [comment]
Sounds good - closing then.
