### ISSUE TITLE
merge next branch of gcsim.app into main

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#282]
- [ ] fix viewer on desktop app to accept new debug format
- [x] merge next branch of gcsim into main
- [ ] add import from GO (load button to load data, add button will search both new char and imported char)
- [x] confirm aws store still works with webapp (should)
- [ ] setup cf kv store

Nice to have list
- [ ] export dynamodb and load into kv store, preserve keys
- [ ] link viewer share to kv store
- [ ] add ability to perm link (with API key)
- [ ] add management interface to perm selected link/hash (with API key)

**Comment by Tsym-or-Tysm** [comment]
Feels like this should go in the gcsim.app repo and not here...

**Comment by srliao** [comment]
oh well it's done now anyways xD
