### ISSUE TITLE
Snapshot Mods Aren't Grouped Together in Logs

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#287]
Snapshot mods are not grouped together in the logs so they're scattered throughout the log instead of being grouped together like pre-damage mods.

![image](https://user-images.githubusercontent.com/84653157/154784478-584f181d-f1cc-429d-9ca6-0b4b6a80e18b.png)

**Comment by srliao** [comment]
#316 should have fixed this as well
