### ISSUE TITLE
Target Initialization Bugs?

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#291]
Code looks kinda weird...

![image](https://user-images.githubusercontent.com/84653157/154824597-bb77bc3d-56c4-4a6c-8aeb-2d395ec5fa24.png)

**Comment by Tsym-or-Tysm** [comment]
It appears that target 1 is getting placed at (0,0), and target is getting placed at (0.6,0).

![image](https://user-images.githubusercontent.com/84653157/154825195-ab68d61a-d42e-4e09-a584-788055dea0b8.png)

![image](https://user-images.githubusercontent.com/84653157/154825204-7a092ed5-94ef-47df-99e6-4df1d25cb728.png)

Probably want to make this consistent at some point eventually, but for now I'm just going to leave it as-is.

**Comment by srliao** [comment]
will tackle this one together with the infusion check mini refactor

**Comment by srliao** [comment]
no longer relevant
