### ISSUE TITLE
Add error message in debug for stuck on energy in sequential mode

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#301]
Title - should be similar to the swap error message

**Comment by Tsym-or-Tysm** [comment]
Leaving idea here - there should be an error log message that gets carried over across iterations, incrementing a timer +1 if it's still stuck. At the end we should only show a single debug message, perhaps with an obvious sign that it was bricking the rotation like "Execution Halted for X Frames Because of Reason Y"

**Comment by srliao** [comment]
can't we just log this instead? like log some kind of statistics on number of frames the sim is stuck waiting for energy for each run, and then present that in the summary screen? imo that would be more useful no?

**Comment by Tsym-or-Tysm** [comment]
It should be available in both places. I have another idea related to what we should show on the summary screen - just need to flesh it out.
