### ISSUE TITLE
Standardize Cooldown System to Use Shenhe System

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#310]
I felt like this was going to get forgotten unless I make an issue about it...

**Comment by soloxcx** [comment]
What does this mean?

**Comment by Tsym-or-Tysm** [comment]
@soloxcx As part of the Shenhe mess, srl had to implement a new cooldown system for her that we were going to use for all characters after we confirmed that there were no bugs. It just seems that we should merge all that in soon so there's no dev confusion.
