### ISSUE TITLE
Xiao charge attack animation cant be cancelled

### ISSUE THREAD

**Issue by agm-bioinfo** [genshinsim/gcsim#328]
As of right now the sim doesn t allow for xiao charge attack animation to be cancelled by a high_plunge action, making the whole string of N1CJHP 155 frames total instead of the 125 reported by xiao mains [frame data](https://docs.google.com/spreadsheets/d/1f3bHBnAMd55OAo9ry62UdO7eWE3AwyHWmmQq73HdwSQ/htmlview#) of this combo

**Comment by agm-bioinfo** [comment]
To add to this, N1 frames are also wrong, both hits should have a spacing of around 13 frames between them. Another important part would be the ability to cancel this attack after the first hit registers.

**Comment by HanSeoulOh** [comment]
Damnnn this is super technical. Thanks for sharing this. This is the kind of stuff the devs can't figure out alone.

**Comment by k0l11** [comment]
related to #209
I've recorded a video of pretty much all Xiao cancels (check my comment there), so his frames will be fixed eventually.
