### ISSUE TITLE
Tags Are Not Visible In Debug Mode

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#329]
They should be noted somewhere to promote visibility. Can probably provide a thin set of getter/setters around Tags for this purpose?

**Comment by srliao** [comment]
wait.. like the character tags? were they ever in debug? i don't recall this

**Comment by Tsym-or-Tysm** [comment]
They were never in debug, but they should be noted somewhere.

**Comment by k0l11** [comment]
At this point, this is possible via `.<char>.tags.<tagkey>`, example: `.ayaka.tags.shenhe-quill` refers to the amount of shenhe quillls ayaka has.
