### ISSUE TITLE
Weapon Characteristics Are Not Available in APLs

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim#331]
I think this one is low priority, but the big one is TTDS cooldown - there's no way of checking whether TTDS is about to come off cooldown in APLs.

I'm split 50-50 on whether we should fix this because functionally in game no one tracks this CD explicitly - it's more tied to other things, but maybe something to think about.

**Comment by srliao** [comment]
system is in place now. just need to go through and add whatever is needed for each weapon one at a time
