### ISSUE TITLE
Alternate Weapon Titles

### ISSUE THREAD

**Issue by FYCZephyr** [genshinsim/gcsim#337]
Some weapons have very long names and/or highly common and well known abbreviations. It would aid ease of writing and minimize spelling errors if the config could support weapon names such as favlance, favsword, sacsword, and ttds etc. in addition to their full titles.

**Comment by srliao** [comment]
#162 related to this. not a trivial change though so won't be any time soon

**Comment by srliao** [comment]
system in place for this now
