### ISSUE TITLE
Substat optimizer sometimes producing unusual results for this config (jade cutter Ayaka freeze) 

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#339]
originally from Kolibri#7675 on discord

using the v0.5.4 .exe and this [config](https://gcsim.app/viewer/share/perm_tzYy03-5ziZtiyjA15sD9)

This particular config is jade cutter Ayaka freeze so it makes sense that Ayaka would likely not want any fluid crit subs. Under usual circumstances the optimizer produces a result like the one above (no fluid crit subs on Ayaka, 103.8k dps) but after repeated attempts it sometimes produces a config like [this](https://gcsim.app/viewer/share/perm_O1aKZRVz3Y0_jx6xpMQwh) with 6 fluid crit subs on Ayaka and 99.9k dps. To me that seemed like enough of an outlier worth reporting, let me know if there's something else I can provide that helps investigate the issue (if there is one)?

**Comment by k0l11** [comment]
fyi, this is still possible on rewrite

**Comment by k0l11** [comment]
Fixed by #1890.
