### ISSUE TITLE
Ganyu ult field starts counting too early

### ISSUE THREAD

**Issue by Charlie-Zheng** [genshinsim/gcsim#340]
Ganyu ult field starts from when her ult cast ends in game. https://youtu.be/ZI2EESRLxlM

In the sim, it starts counting from when the CD starts. https://gcsim.app/viewer/share/knWkhUH73b3AeThCW-Rdv

**Comment by jordanlovato** [comment]
@Charlie-Zheng Just tested and seems resolved already: https://gcsim.app/viewer/share/perm_eImqH9U-EtT580zy90eJj

Could you confirm for me? The original debug log has since expired xD

**Comment by jordanlovato** [comment]
Frames update will also help us more accurately track Ganyu burst: https://github.com/genshinsim/gcsim/pull/448
