### ISSUE TITLE
Jean Ult does not self-swirl

### ISSUE THREAD

**Issue by LettuceHunt** [genshinsim/gcsim#381]
would like to sim sunfire teams!

**Comment by k0l11** [comment]
Doesn't #426 close this issue?

**Comment by HanSeoulOh** [comment]
> Doesn't #426 close this issue?

I believe right now it's sort of a inbetween solution for now. Sunfire will work but some other self swirl interactions may not. Should we close for now? @srliao

**Comment by srliao** [comment]
oops forgot to close
