### ISSUE TITLE
bennett vaping when should be melt on double aura (frozen + hydro)

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#405]
https://gcsim.app/viewer/share/perm_wE4ONvDu2uA73NTiPioM3

![image](https://user-images.githubusercontent.com/906239/159810584-56461226-71dc-47af-94b1-e32b7ee481fa.png)

2x should be applied but 1.5 got applied probably because of the vape follow up

![image](https://user-images.githubusercontent.com/906239/159810628-589aae4c-6e25-4863-a1d8-7426c7064bf5.png)

**Comment by vinc-dev** [comment]
https://gcsim.app/viewer/share/jYds5QPu4pGWkNHmhneUv
Trying to fix this locally. Here's the result. Can you help to check if this is correct?
