### ISSUE TITLE
Add an option to miss an ability

### ISSUE THREAD

**Issue by emcey** [genshinsim/gcsim#406]
Purpose is to not use up elemental aura in certain situations.

**Comment by tzwang1** [comment]
Looks like a duplicate of #195

**Comment by emcey** [comment]
Sorry, I didn't see that one. Do you have any idea if this is something that will happen in the near future?

**Comment by tzwang1** [comment]
No worries. I actually just started contributing this week, so not too sure what the status is for things. Maybe someone who has been working on the project longer would have a better idea.

**Comment by shizukayuki** [comment]
Closing as duplicate of #195.

> Sorry, I didn't see that one. Do you have any idea if this is something that will happen in the near future?

not anytime soon afaik, will have to ask @srliao.
