### ISSUE TITLE
Sara's burst does its damage at the same time its cooldown begins

### ISSUE THREAD

**Issue by emcey** [genshinsim/gcsim#413]
Sara's burst should calculate and display its damage when her burst cooldown begins 50 frames after cast, but according to the sim, it happens 86 frames after the cooldown begins. This results in a 136 frame difference between casting her burst and doing damage, which is inaccurate. I can provide video evidence if needed.

**Comment by HanSeoulOh** [comment]
thanks for your contribution, I recommend you submit video evidence for completeness but the devs will probably just take your word for it
