### ISSUE TITLE
A problem about Kujou Sara 's burst

### ISSUE THREAD

**Issue by kawayiYokami** [genshinsim/gcsim#446]
in game  , Kujou Sara 's burst "subjugation：KouKou Sendou"  is able to buff (crowfeather cover) two character if player swap as quickly as possible.

such as  
"active Sara , Sara burst 
 swap to Yae ， Yae skill,
 swap to Raiden Shogun , Raiden Shogun burst "

both Yae and Raiden Shogun should receive buff “crowfeather cover”. 

but i dont know how to code this special cases and make my gcsim work correctly.

a same problem happen to fischl( i always team up sara & fischl & yae & raiden shogun , i like thunder team!)

**Comment by bryanck29** [comment]
@kawayiYokami 
![image](https://user-images.githubusercontent.com/44809181/162592001-bf3134d5-d6d0-468f-bcad-1a011a2b44ad.png)

someone cmiiw.

**Comment by kawayiYokami** [comment]
@bryanck29

thank you so much!
