### ISSUE TITLE
Itto C1 charges not count on burst

### ISSUE THREAD

**Issue by jud1** [genshinsim/gcsim#495]
problem with the C1 on itto:

_After using Royal Descent: Behold, Itto the Evil!, Arataki Itto gains 2 stacks of Superlative Superstrength. After 1s, Itto will gain 1 stack of Superlative Superstrength every 0.5s for 1.5s._

burst starts with 2 charges and gains 3 over time (1.5s)

if burst->skill = 4 charges, instant 7 charge attak without any normal attak

**Comment by bryanck29** [comment]
is this the correct implementation? 
https://gcsim.app/viewer/share/fo0fNBdnz-unb099o7ctL

tested it with this combo string for c2:
Q E SCA5+F N4 SCA4+F E SCAF

haven't check the frame data tho.

**Comment by k0l11** [comment]
maybe this is fixed by #661?
