### ISSUE TITLE
Add a param for Childe activating E while moving or not (but maybe don't make it 1 frame)

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#498]
Childe's skill, if activated while moving, is 1 frame long. The user should have the option to do this

However, making it 1 frame in the sim will cause issues with stealing vaporizes from his burst in the common sequence `burst, skill`. This interaction is verifiable in game, but I'd rather not have every Childe user be forced to type a `wait` in order for the skill to not damage before his burst lands. So maybe make his moving skill long enough that this doesn't happen (5 frames?)

Also I think his "moving" skill should be the default behavior and "nonmoving" should be the param e.g. `skill[nonmoving=1]`

**Comment by k0l11** [comment]
related to #209 
Idk about artificially extending his E when walking. If burst followed by skill with no wait results in the E stealing a vape ingame, then it should do the same in the sim. Every Childe user would also wait/dash/... ingame, so the same should be done in the sim. Can't say much about what the default behaviour should actually be, but I think the user either has to manually input `walk, skill` or it will be handled via a parameter like you said.

**Comment by k0l11** [comment]
The initial confusion is something that I wouldn't mind if it means being accurate to how it is ingame.

**Comment by k0l11** [comment]
check if this is still an issue once #667 is merged
