### ISSUE TITLE
Instructors does not activate on freeze

### ISSUE THREAD

**Issue by Charlie-Zheng** [genshinsim/gcsim#546]
https://gcsim.app/viewer/share/qdJL7RLJ3UeG1clQRIBbo

In this sim, at frame 1100, Eula procs freeze with 4pc Instructors equipped, but does not activate the effect.

![image](https://user-images.githubusercontent.com/16330291/168188684-78592300-ab06-468b-b981-4fee3327621c.png)
![image](https://user-images.githubusercontent.com/16330291/168188692-1b254dde-dddb-485d-a35f-ef62266cbe15.png)

**Comment by RarePossum** [comment]
https://gcsim.app/viewer/share/K8_X7NEDTwn_VBukT_rLk Adding another sim to demonstate
