### ISSUE TITLE
EC and Frozen aura interaction is not accurate

### ISSUE THREAD

**Issue by Karashina** [genshinsim/gcsim#557]
If you apply electro to frozen & hydro aura coexisting, SC should happen, but EC happens first.

https://cdn.discordapp.com/attachments/884485336657444894/975496360134594580/unknown.png
sim tries EC before SC ...as far as I told

I'm sorry that my english is potato quality...

**Comment by Charlie-Zheng** [comment]
https://gcsim.app/viewer/share/TrYSmZ3yRHtI0j8PaWpTx

This sim demonstrates the bug at frame 170

**Comment by Charlie-Zheng** [comment]
https://cdn.discordapp.com/attachments/884485336657444894/975495988406009936/2022-05-15_15-30-24.mp4
This video shows both EC and SC happening
![image](https://user-images.githubusercontent.com/16330291/168494886-913ecc53-8c19-4c27-ad12-e2d5d78b03bf.png)
