### ISSUE TITLE
'hurt every interval' is not reducing serpent spine stacks

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#564]
https://gcsim.app/viewer/share/perm_I7xc-9sBQQc1Lsv3IlBwU

eula is at full stacks for the entire sim duration

**Comment by k0l11** [comment]
blocked by https://github.com/genshinsim/gcsim/issues/836

**Comment by k0l11** [comment]
no longer a bug since the original feature does not exist anymore
