### ISSUE TITLE
'hurt every interval' is not being queued at the correct intervals

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#565]
https://gcsim.app/viewer/share/perm_I7xc-9sBQQc1Lsv3IlBwU

this config is using `hurt every interval=0,1200 amount=0,3000;`

but note that 1) a hurt queue is always happening at 0 frames and 2) there are several intervals where hurt queues occur in rapid succession such as frames 105, 125, and 161

**Comment by k0l11** [comment]
blocked by #836

**Comment by k0l11** [comment]
no longer a bug since the original feature does not exist anymore
