### ISSUE TITLE
Super high refine sac sword cd behaves irregularly

### ISSUE THREAD

**Issue by RarePossum** [genshinsim/gcsim#598]
https://gcsim.app/viewer/share/perm_1Ag1n1Vv-v4u8iUVd9Hz2
CD isn't resetting properly. Compare it to an R20 sacsword.
https://gcsim.app/viewer/share/perm_1Ag1n1Vv-v4u8iUVd9Hz2

**Comment by k0l11** [comment]
This is a bug but it will not be fixed, because it requires restricting user input everywhere in order to avoid overflows/underflows. This is something that we will not do.

**Comment by k0l11** [comment]
closing as wontfix
