### ISSUE TITLE
Yelan c6 not working properly

### ISSUE THREAD

**Issue by IvanHdzF** [genshinsim/gcsim#601]
Yelan c6 is doing some 0 damage procs  on the BBs, and past first rotations it doesnt triggers on instances where it should.

Link
https://gcsim.app/viewer/share/IC_kAAkybngLgcDupzAcy

**Comment by srliao** [comment]
putting a perm link here https://gcsim.app/viewer/share/perm_3t_rsX1nUvYZya2Nao8KT

**Comment by RarePossum** [comment]
Every 0 damage barb comes has damage_grp_mult=0 while the ones that do damage have damage_grp_mult=1 tahts what I've spotted.

**Comment by srliao** [comment]
Two bugs here.

ICD group should be all 1's here: https://github.com/genshinsim/gcsim/blob/be5c9954e3826485b931e7e07953d6a64dd804ed/pkg/core/icd.go#L134

`c.c6count` should be reset to 0 here: https://github.com/genshinsim/gcsim/blob/be5c9954e3826485b931e7e07953d6a64dd804ed/internal/characters/yelan/abil.go#L249

**Comment by srliao** [comment]
turn out icd was correct. yelan c6 uses default group instead of yelan breakthrough group
