### ISSUE TITLE
kazuha c6 should be added via predamagemod

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#605]
title

currently:

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/906239/174798282-49d532b4-52d9-40de-9f80-9adda52d08a6.png">

**Comment by k0l11** [comment]
Since the PreDamageMod design pattern was abandoned (#496), shouldn't this issue be closed? I rewrote this part of Kazuha C6 to use AttackMod.
