### ISSUE TITLE
fix AoE/hitbox data

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#611]
The AoE/hitboxes of abilities in the sim are often arbitrary. This should be eventually changed to match the actual data for all characters.
- [ ] albedo
- [ ] aloy
- [ ] amber
- [ ] ayaka
- [ ] ayato
- [ ] barbara
- [ ] beidou
- [ ] bennett
- [ ] candace
- [ ] chongyun
- [ ] collei
- [ ] cyno
- [ ] diluc
- [ ] diona
- [ ] dori
- [ ] eula
- [x] fischl
- [ ] ganyu
- [ ] gorou
- [ ] heizou
- [ ] hutao
- [ ] itto
- [ ] jean
- [ ] kaeya
- [ ] kazuha
- [ ] keqing
- [ ] klee
- [ ] kokomi
- [ ] kuki
- [ ] layla
- [ ] lisa
- [ ] mona
- [ ] nahida
- [ ] nilou
- [ ] ningguang
- [ ] noelle
- [ ] qiqi
- [ ] raiden
- [ ] razor
- [ ] rosaria
- [ ] sara
- [ ] sayu
- [ ] shenhe
- [ ] sucrose
- [ ] tartaglia
- [ ] thoma
- [ ] tighnari
- [ ] traveleranemo
- [ ] travelerdendro
- [ ] travelerelectro
- [ ] travelergeo
- [ ] venti
- [ ] xiangling
- [ ] xiao
- [ ] xingqiu
- [ ] xinyan
- [ ] yaemiko
- [ ] yanfei
- [ ] yelan
- [ ] yoimiya
- [ ] yunjin
- [ ] zhongli

originally about Hu Tao CA AoE:
When uncancelled, you could maybe make it hit multiple enemies if you're lucky but when cancelled with Jump/Dash this choice becomes very questionable.

**Comment by RarePossum** [comment]
Also applies to Kazuha's N1 at least, maybe other attacks.

**Comment by JohnJillky** [comment]
Yeah a lot of attacks seem to be unrealistically categorized as AoE. E.g., I can have Eula autoing on 5 enemies and gcsim thinks she hits all 5. In practice, you might get more like 2-3, and often 1. I think the "AoE-ness" of attacks should be adjustable
