### ISSUE TITLE
Kokomi E DMG should be affected by Kokomi Q

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#615]
"Kokomi's E snapshots, but does not resnapshot upon Q cast when refreshing the Bake-Kurage duration and the damage dynamically changes while Q is active." from [KQM TCL](https://library.keqingmains.com/evidence/characters/hydro/kokomi#skill-mechanics-1).

Sim: https://gcsim.app/viewer/share/perm_RF0x6GHof5wKuuQsNGInt
Kokomi's E damage is 2191 all the time in this sim, even when Kokomi's Q is active.

originally found by Xardas#5785:
https://discord.com/channels/845087716541595668/869210750596554772/980659723294625863

**Comment by shizukayuki** [comment]
should be fixed by #626 or srliao/gcsim#21 in the rewrite.
