### ISSUE TITLE
Zhongli Skill no longer supports the max parameter

### ISSUE THREAD

**Issue by RarePossum** [genshinsim/gcsim#627]
In the documentation, it states that "max" is a parameter for Zhongli's skill to determine the maximum number of resonances. https://docs.gcsim.app/reference/characters/status_tags_param_master

This no longer exists. Or it was renamed and the documentation is now wrong
![image](https://user-images.githubusercontent.com/48541822/178088733-e13d0f91-7525-4370-8217-8ff01947a465.png)

**Comment by shizukayuki** [comment]
it was renamed to `res_count` in 1225d52 and the docs haven't been updated since March.
