### ISSUE TITLE
[Rewrite] Thoma Fiery Collapse damage calculation is missing several multipliers

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#642]
https://gcsim.app/viewer/share/6ikJsaoJdwIuKcEGF26pX

![image](https://user-images.githubusercontent.com/58927267/180216557-465e888d-d2bf-459b-95c8-8280722827d9.png)

Fiery Collapse damage seems unusually low.

![image](https://user-images.githubusercontent.com/58927267/180216746-7f15437f-cfc1-4800-b6d9-1f211200a979.png)

In the calc debug display several fields like attack are zero

**Comment by k0l11** [comment]
this will be fixed by #684
