### ISSUE TITLE
[Rewrite] Eula frames for A1 proc appears off

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#643]
https://gcsim.app/viewer/share/ErMWqIfTPBY5Y2RpFZiE0

![image](https://user-images.githubusercontent.com/58927267/180218640-b4500a13-0ed9-4ff5-8a7f-472e6e3d5a1c.png)

When Eula uses hold E with 2 Grimheart stacks, her A1 activates 5 frames after the 2nd Icewhirl which seems unusually fast. She doesn't get a burst stack from it either

**Comment by srliao** [comment]
should be fixed now. merged in https://github.com/srliao/gcsim/pull/21
