### ISSUE TITLE
Hu Tao ult doesn't seem to increase paramita buff duration on cast

### ISSUE THREAD

**Issue by leepc12** [genshinsim/gcsim#647]
![image](https://user-images.githubusercontent.com/8625660/181865296-24d51638-6400-4005-be91-bb08fe3febc3.png)

Spirit Soother damage is noticeably low even when it's cast before the Paramita buff expires.
When I use N1CD instead of the ult then her charged attack gets the paramita buffs.

https://gcsim.app/viewer/share/perm_kSFmnWt2x_piruCqjZPk-

**Comment by k0l11** [comment]
this combo works in rewrite with updated frames + hitlag on hu tao
https://next.gcsim.app/v3/viewer/share/a6f031fc-2fd6-4ee8-9036-5e602469ec6c
