### ISSUE TITLE
reaction damage melt/vape multiplier not applied

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#65]
![](https://media.discordapp.net/attachments/869210750596554772/907769249735540756/unknown.png)

Also check to see if aoe reaction damage is using correct stats?

**Comment by Tsym-or-Tysm** [comment]
Did some digging on this, and it appears to be related to the 4VV 60% swirl bonus not proccing on the AoE damage instances. Since you're reworking the reactions system I'm not bothering to make any changes here just FYI, so I guess just keep that interaction in mind as you're doing the rework.

**Comment by srliao** [comment]
not sure if this one is still bugged. @Tsym-or-Tysm you wouldn't happen to remember the config that caused this?

**Comment by Tsym-or-Tysm** [comment]
Just checked Sukokomon and this one looks fixed to me with the refactor. Closed.

![image](https://user-images.githubusercontent.com/84653157/149053970-ec3071ec-8ae7-45d6-b072-828658e6fcf6.png)
