### ISSUE TITLE
Raiden E Eye should be affected by hitlag

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#657]
I think it's reasonable to assume that since Raiden E's burst dmg buff gets extended by hitlag, the eye dmg part should as well. How exactly the dmg icd works still needs to be investigated.
relevant: https://docs.google.com/spreadsheets/d/1Xxp_SywwuzFEbhHlemNXQdR3o9Jctf1-gRjRF9aolMs/edit#gid=0

**Comment by k0l11** [comment]
related to #658

**Comment by srliao** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/906239/184913622-54d32af3-ebb5-4970-8159-1ba47986d562.png">


As discussed here, leaving the issue for now until a later date when I have time to investigate

**Comment by k0l11** [comment]
After more investigation, I've come to the conclusion that the eye status and the eye dmg buff status should both be hitlag extendable. The dmg icd should not be hitlag extendable. This means I'm removing the eye status in favor of just reusing the eye dmg buff status. The eye procs only if the eye dmg buff status is active on the character whose dmg is proccing the eye.
