### ISSUE TITLE
missing hitlag

### ISSUE THREAD

**Issue by k0l11** [genshinsim/gcsim#658]
chars:
- [ ] itto
- [ ] heizou
- [x] hutao
- [ ] kuki
- [ ] noelle
- [ ] shenhe (depends on #654)
- [ ] tartaglia 
- [ ] traveleranemo
- [ ] travelerelectro
- [ ] travelergeo
- [ ] yoimiya

weapons:
- [ ] wine and song stam percent mod
- [ ] amenoma kageuchi 30s seed duration timer

artifacts:
- [ ] 4 tom shield bonus mod

**Comment by srliao** [comment]
close this in favour of consolidated tracking in #699
