### ISSUE TITLE
Eula hold E with 1 or 2 grimheart stacks does not generate particles

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#709]
https://next.gcsim.app/v3/viewer/share/7278c79c-b6f8-47fc-bd88-e378436fb402

first cast -- hold e with no grimheart, generates particles
next cast -- hold e with 1 grimheart, no particles
next cast -- hold e with 2 grimheart, no particles

edit -- there seems to be an issue with viewing and generating next.gcsim.app links at the time of writing

**Comment by k0l11** [comment]
will be fixed by #711
