### ISSUE TITLE
Import from Enka Bug

### ISSUE THREAD

**Issue by s-naveen** [genshinsim/gcsim#742]
If any of the character imported from enka has some unrecognized weapon like waster greatsword/dull blade etc, then import is not working and following error thrown on console. 

![image](https://user-images.githubusercontent.com/7128309/184556878-677766e2-450e-4f3b-bee4-27bc1d56b495.png)

**Comment by k0l11** [comment]
@ChinPTeo is this fixed?

**Comment by ChinPTeo** [comment]
tested on gcsim.app using 600047081

itto seems to work
