### ISSUE TITLE
[Feature Request] Buff durations

### ISSUE THREAD

**Issue by AerinSJ** [genshinsim/gcsim#77]
A visual indicator, in debug mode, to indicate when a buff is active and expires.

E.g. when Bennett burst is active and when it expires, for easier cross checking against config files whilst debugging, to determine exactly which frames are needed for tweaks

Similarly, debuffs too if plausible, e.g. when VV expires for a specific element, so rotations can be tailored to maintain high uptime on VV debuffs.

**Comment by Tsym-or-Tysm** [comment]
Had a conversation about this on Discord. See here for the start.

https://discord.com/channels/845087716541595668/886303126242623540/930652840974745670

Current consensus I think is that it would be difficult and would require multiple changes, but is possible.

Not 100% sure where this falls on the roadmap though, but this is probably going to be delayed a bit as this will need to live separate from the current debug view and will also be a difficult chart to put together while also looking good.

**Comment by srliao** [comment]
![image](https://user-images.githubusercontent.com/906239/155609888-4cc59cb2-ebb3-44b9-a07a-eea6b1f48212.png)

added a basic implementation

**Comment by srliao** [comment]
Added the tracking thing on the left so closing this for now. Plan on adding some sort of custom canvas to track buff horizontally in the future on UI
