### ISSUE TITLE
Ayato A4 weirdness

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#854]
ayato a4 appears to either 1) sometimes not activate more than once or 2) not activate in 1s intervals and im not sure why.

config where a4 activates once and never again: https://gcsim.app/v3/viewer/share/2d785002-ffa1-4ed3-b17a-e9dd371e7dbf

config where a4 activates at odd frame intervals: https://gcsim.app/v3/viewer/share/785c6658-e9cb-449a-8ead-57b2f75096cd

first one is 72 frames after swap, then 113 frames later, then 85... shouldn't it always be 60 frames?

**Comment by k0l11** [comment]
His A4 is coded in a weird way, I'll be fixing and rewriting it.
