### ISSUE TITLE
Optimize the prestack parameter for Itto's Burst

### ISSUE THREAD

**Issue by MrPillow1** [genshinsim/gcsim#861]
Currently, if itto does NA > Q, he gets a strStack. This should be changed to

"Itto by default doesn't get any prestacks when doing NA > Q, and the parameter should be used if one wishes to pefrom the prestack technique."

This is because in-game, you need to time the burst in a delibirate manner if you want to perform the prestack technique, so this should be reflected in gcsim too.

**Comment by k0l11** [comment]
this will be fixed by #729. you'll have a parameter called "prestack" on itto's burst that is 0 by default and if it's not 0, it'll add a stack if you did N1 -> Q
