### ISSUE TITLE
Childe C4 timer is being delayed by hitlag and can be applied multiple times on the same target

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#866]
https://gcsim.app/v3/viewer/share/03bd08c5-983f-4adf-b05f-85a17eef2bb0

in this config, childe applies riptide and stands there for a bit. C4 activates every 240 frames like normal

later, he applies riptide and bennett starts attacking. C4 starts triggering 143 frames later, then 158 frames, then 133...

I think there are 2 issues at play here:
1) C4 is wrongly being delayed by hitlag 
3) the target ended up having 2 instances of C4 active on them at the same time

**Comment by k0l11** [comment]
Do you have footage showing that the 4s timer it isn't delayed by hitlag?

**Comment by soloxcx** [comment]
no, it was just an assumption. I can record a test in a few hours though.

**Comment by k0l11** [comment]
I fixed 2., but for 1. I'd need a video to confirm.

**Comment by soloxcx** [comment]
https://www.youtube.com/watch?v=YUVhVCYDduM
https://www.youtube.com/watch?v=6cI0qiX5vKU

looks like it is delayed by hitlag. the frame count begins when the riptide symbol gets larger

vid 1:
(no attacking)
705
939 | 234 frames since last proc
1174 | 235 frames since last proc
(attacking)
1459 | 285 frames since last proc
1753 | 294 frames since last proc

vid 2:
(no attacking)
667
902 | 235 frames since last proc
1136 | 234 frame since last proc
(attacking)
1429 | 293 frames since last proc
1726 | 297 frames since last proc


im not sure if i'm experiencing frame skips or if the proc is supposed to be 235 frames instead of 240 lol. so that's why i recorded it twice

**Comment by k0l11** [comment]
looks like it's ticking every 3.9s instead of 4s, I've adjusted that as well
