### ISSUE TITLE
Keqing can't 5N1C during infusion

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#884]
https://gcsim.app/v3/viewer/share/fe42be47-7939-4e29-91e6-a5ec458e83b3

infusion expires during last CA animation

vid of her doing 5n1c without hitlag https://www.youtube.com/watch?v=zjm_YreBK9k

**Comment by k0l11** [comment]
Her last CA is still electro, so I don't see the problem?

**Comment by soloxcx** [comment]
oops, i need to read a little more closely
