### ISSUE TITLE
Skyward Atlas's first instance of damage should be 155f after proc, then in 147f intervals

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#929]
https://gcsim.app/v3/viewer/share/e04fc2f9-7074-4ff2-a5fe-b67144c0ed60

currently atlas does damage the same frame it procs

video of how it works in game: https://youtu.be/ncqhoqk6O14

proc = 135f
1st attack fires = 290f | 155f after proc
2nd attack fires = 437f | 147f after 1st
3rd attack fires = 584f | 147f after 2nd
4th attack fires = 731f | 147f after 3rd
5th attack fires = 878f | 147f after 4th
6th attack fires = 1025f | 147f after 5th

**Comment by k0l11** [comment]
the proc was actually at 142f, so you get a consistent ~147f gap between procs

**Comment by soloxcx** [comment]
> the proc was actually at 142f, so you get a consistent ~147f gap between procs if we ignore the first proc being ~148f after proc

oh, good catch, klee's weapon fading away made me think it was the proc
