### ISSUE TITLE
Missing characters to be implemented

### ISSUE THREAD

**Issue by srliao** [genshinsim/gcsim#94]
- [x] Sayu
- [x] Thoma
- [x] Traveler (Geo)
- [x] Traveler (Electro)
- [x] Traveler (Anemo)
- [x] Razor
- [x] Barbara
- [x] Xinyan
- [x] Mona
- [x] Ayaka C1 to C6
- [x] Kazuha C1 to C6
- [x] Gorou
- [x] Itto
- [x] Shenhe
- [x] Yunjin
- [x] Yae
- [x] Ayato

### Released Soon
- [x] Kuki
- [x] Heizou

**Comment by HanSeoulOh** [comment]
Barbara tracked in PR #101

**Comment by srliao** [comment]
958466f adds mona but no c1/c6/a4 yet (leave for now)

**Comment by srliao** [comment]
#107 adds geo traveler

**Comment by HanSeoulOh** [comment]
Itto tracked in PR #140

**Comment by HanSeoulOh** [comment]
Yae tracked in PR #169

**Comment by srliao** [comment]
emc tracked in #391

**Comment by srliao** [comment]
thoma tracked in #410

**Comment by imring** [comment]
sayu tracked in #451

**Comment by imring** [comment]
razor tracked in https://github.com/srliao/gcsim/pull/4

**Comment by imring** [comment]
xinyan tracked in https://github.com/genshinsim/gcsim/pull/617
