### ISSUE TITLE
Kazuha A4 does not distinguish between % based EM buffs and flat EM buffs

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#971]
https://gcsim.app/v3/viewer/share/a8119d88-4f85-4fdc-9591-69073aa8aeec

in this config, Kazuha A4 is being boosted by Sucrose A4 which is not supposed to happen

> //this ignores any EM he gets from Sucrose A4, which is: When Astable Anemohypostasis Creation
//- 6308 or Forbidden Creation - Isomer 75 / Type II hits an opponent, increases all party
//members' (excluding Sucrose) Elemental Mastery by an amount equal to 20% of Sucrose's
//Elemental Mastery for 8s.
//
//he still benefits from sucrose em but just cannot share it

this is commented above Kazuha A4's code but is not actually implemented

**Comment by k0l11** [comment]
closing in favor of #1016
