### ISSUE TITLE
Burgeon and rupture do not do self damage

### ISSUE THREAD

**Issue by skippi** [genshinsim/gcsim#985]
Both of these reactions need to damage the user by 5% of the burgeon's original damage. Damage reduction (XQ, Beidou, etc) does not work to reduce their damage. The 5% calc is already in code, just need to program in the self damage (along with calcs). Probably best to program this as a drain and just emit `OnCharacterHurt` for simplier implementation.

**Comment by k0l11** [comment]
blocked by #1131

**Comment by k0l11** [comment]
should be done via #1655
