### ISSUE TITLE
Gadgets being hit are logged in the debug

### ISSUE THREAD

**Issue by soloxcx** [genshinsim/gcsim#992]
https://gcsim.app/v3/viewer/share/a69bc4b4-4387-4c46-b815-f727333e6fd8

gadgets being hit are logged with 0 damage, example with guoba active
![image](https://user-images.githubusercontent.com/58927267/193894163-50e8efa5-1505-455e-9e59-6f79b826b69b.png)
I think gadgets being hit should not get logged, or at least not in this way because the current format will confuse readers.

**Comment by k0l11** [comment]
fixed by #1040
